<project name="ProjectSWP" default="default" basedir=".">
    <description>Builds the project ProjectSWP.</description>

    <!-- Define directory locations -->
    <property name="src.dir" value="src/java"/>
    <property name="build.classes.dir" value="build/web/WEB-INF/classes"/>
    <property name="lib.dir" value="lib"/>

    <target name="clean">
        <delete dir="${build.classes.dir}" />
    </target>

    <target name="compile">
        <mkdir dir="${build.classes.dir}" />
        <javac srcdir="${src.dir}" destdir="${build.classes.dir}" includeantruntime="false">
            <classpath>
                <fileset dir="${lib.dir}">
                    <include name="**/*.jar" />
                </fileset>
            </classpath>
        </javac>
    </target>

    <target name="default" depends="clean, compile" />
</project>
