name: Java CI with Ant and SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Sonar packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build with Ant
      run: ant -buildfile ProjectSWP/build.xml

    - name: Run SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=ProjectSWP
          -Dsonar.sources=src/java
          -Dsonar.java.binaries=build/web/WEB-INF/classes
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=<tên_organization>
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
